# Generated by Django 4.2.20 on 2025-03-13 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learneaseapp', '0003_quizsubmissionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=100)),
                ('quiz_title', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
