# Generated by Django 4.2.20 on 2025-03-13 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learneaseapp', '0004_quizsubmissionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmissionrecord',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
