# Generated by Django 4.2.20 on 2025-03-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learneaseapp', '0005_quizsubmissionrecord_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmissionrecord',
            name='quiz_last_updated',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
