# Generated by Django 4.2.20 on 2025-03-14 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learneaseapp', '0006_quizsubmissionrecord_quiz_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizassignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learneaseapp.course'),
            preserve_default=False,
        ),
    ]
